@startmindmap

* 队列（queue）
** 先进先出，是一种操作受限的线性表数据结构
** 入队enqueue:向队列尾部放入数据 出队dequeue:从队列头部取出数据
** 顺序队列和链式队列
** 循环队列
*** 可避免数据搬移
** 阻塞队列
*** 队列为空的时候，从队头取数据会被阻塞。如果队列已经满了，那么插入数据的操作就会被阻塞
** 并发队列
*** 线程安全的队列我们叫作并发队列。利用 CAS 原子操作，可以实现非常高效的并发队列



@endmindmap
