@startmindmap

* 哈希算法

** 定义
*** 任意长度的二进制值串映射为固定长度的二进制值串

** 要求
*** 从哈希值不能反向推导出原始数据
*** 对输入数据非常敏感，哪怕原始数据只修改了一个 Bit，最后得到的哈希值也大不相同
*** 散列冲突的概率要很小，对于不同的原始数据，哈希值相同的概率非常小
*** 哈希算法的执行效率要尽量高效，针对较长的文本，也能快速地计算出哈希值

** MD5

** 应用
*** 安全加密：MD5 SHA 等
*** 唯一标识：文件的MD5值
*** 数据校验：BT下载的文件验证
*** 散列函数
*** 负载均衡
*** 数据分片
**** 统计“搜索关键词”出现的次数；快速判断图片是否在图库
*** 分布式存储
**** 一致性哈希


@endmindmap
